# Generated by Django 4.1.1 on 2022-09-10 21:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(blank=True, max_length=3000, null=True)),
                ('given_path', models.CharField(blank=True, max_length=3000, null=True)),
                ('absolute_dir', models.CharField(blank=True, max_length=3000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='PreCacheKeyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=3000, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='PreCacheFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_key', models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True)),
                ('fullpath', models.CharField(blank=True, help_text='the original path', max_length=3000, null=True)),
                ('rel_fullpath', models.CharField(blank=True, help_text='the original path, relative to the project root', max_length=3000, null=True)),
                ('path', models.CharField(blank=True, help_text='a posix path without the filename', max_length=3000, null=True)),
                ('rel_path', models.CharField(blank=True, help_text='a posix path without the filename, relative to the root', max_length=3000, null=True)),
                ('anchor', models.CharField(blank=True, help_text='the original drive', max_length=255, null=True)),
                ('filename', models.CharField(blank=True, help_text='the filename with the suffix', max_length=3000, null=True)),
                ('stem', models.CharField(blank=True, help_text='the filename without the suffix', max_length=3000, null=True)),
                ('suffix', models.CharField(blank=True, help_text='The extension including the period', max_length=3000, null=True)),
                ('ext', models.CharField(blank=True, help_text='The extension without the period', max_length=3000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
