# Generated by Django 4.1.1 on 2022-09-11 01:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precachefile',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precachefile',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_path', models.CharField(blank=True, help_text='a posix path without the filename, relative to the root', max_length=3000, null=True)),
                ('rel_fullpath', models.CharField(blank=True, help_text='the original path, relative to the project root', max_length=3000, null=True)),
                ('filename', models.CharField(blank=True, help_text='the filename with the suffix', max_length=3000, null=True)),
                ('stem', models.CharField(blank=True, help_text='the filename without the suffix', max_length=3000, null=True)),
                ('ext', models.CharField(blank=True, help_text='The extension without the period', max_length=3000, null=True)),
                ('bulk_key', models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_key', models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True)),
                ('rel_fullpath', models.CharField(blank=True, help_text='the original path, relative to the project root', max_length=3000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dirs', models.ManyToManyField(blank=True, to='project.directory')),
                ('files', models.ManyToManyField(blank=True, to='project.file')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.directory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
