# Generated by Django 4.1.1 on 2022-09-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_directory_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_path', models.CharField(blank=True, max_length=3000, null=True)),
                ('filename', models.CharField(blank=True, max_length=3000, null=True)),
                ('ext', models.CharField(blank=True, max_length=3000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.file')),
            ],
        ),
        migrations.CreateModel(
            name='FileKeyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=3000, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.file')),
            ],
        ),
    ]
