# Generated by Django 4.1.1 on 2022-09-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_fileoutput_filekeyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileoutput',
            name='auto_build',
            field=models.BooleanField(default=False, help_text='Flag true to convert during parsing.'),
        ),
    ]
