# Generated by Django 4.1.1 on 2022-09-11 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_fileoutput_auto_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileoutput',
            name='bulk_key',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='OutputDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_path', models.CharField(blank=True, help_text='the original path, relative to the project root', max_length=3000, null=True)),
                ('bulk_key', models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dirs', models.ManyToManyField(blank=True, to='project.outputdirectory')),
                ('files', models.ManyToManyField(blank=True, to='project.fileoutput')),
            ],
        ),
    ]
