# Generated by Django 4.1.1 on 2022-09-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_fileoutput_bulk_key_outputdirectory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileoutput',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.file'),
        ),
    ]
