# Generated by Django 4.1.1 on 2022-09-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_fileoutput_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileoutput',
            name='sim_file',
            field=models.BooleanField(default=False),
        ),
    ]
