# Generated by Django 4.1.1 on 2022-09-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_fileoutput_project_outputdirectory_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileoutput',
            name='menu_label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
