# Generated by Django 4.1.1 on 2022-09-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_fileoutput_menu_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputdirectory',
            name='stem',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
